### ISSUE TITLE
ELLIPSE entity is missing in dxf-parser

### ISSUE THREAD

**Issue by cuixiping** [gdsestimating/dxf-parser#10]
Documentation of ELLIPSE from autodesk help center: http://help.autodesk.com/view/ACD/2015/ENU/?guid=GUID-107CB04F-AD4D-4D2F-8EC9-AC90888063AB

**Comment by bzuillsmith** [comment]
Thanks, I've added support for the ELLIPSE entity. Just need to write some tests for it before publishing.

**Comment by bzuillsmith** [comment]
Ellipses are included in the latest release (4.8).
