### ISSUE TITLE
Normalize() group transforms

### ISSUE THREAD

**Issue by minithc** [gdsestimating/dxf-parser#17]
First of all, thank you for an amazing work!

I'm just curious, is it possible to add normalize() function into the library, to unwind... to apply all block transforms to the endpoints and shapes?

Thanks again

**Comment by bzuillsmith** [comment]
This library is mainly focused on parsing the data into an object with the same structure as the original document. I thought I had an example of drawing the effective coordinates in [three-dxf](https://github.com/gdsestimating/three-dxf) but it doesn't look like I ever completed the task of drawing blocks properly. I'll have to work on that a bit more. But in the end, even three-dxf won't do quite what you want. You'll have to write some code to do that separately.

**Comment by bzuillsmith** [comment]
Actually, it looks like three-dxf does make inserts/blocks work and places them properly, but it relies on three.js to do most of the work by using groups. Still, the ground work is in three-dxf if you take a look. Just gotta figure the offsets yourself.

**Comment by minithc** [comment]
Thanks for a reply. I'm using the three-dxf as a example already, and it is self-explainable. Thanks again for an amazing work.

I made an open-source javascript shape offsetting library and trying to finish a free CAM based on your library, and at this point I have to fix small issues like the group transforms. Thanks again for your response!

**Comment by openhardwarecoza** [comment]
Denis, join the world's biggest free cam project on github.com/LaserWeb
(mill, laser, v carve)

Join the revolution instead of starting from scratch

See http://cncpro.co and join the huge g+ Community too

**Comment by minithc** [comment]
Peter, thanks!

Already have the LaserWeb in mind! Tested your app before and it work nicely. I'm just need the CAM for a more specific needs.

**Comment by openhardwarecoza** [comment]
Cool man, do tag me into any news about it would love to see what you are busy with (;

**Comment by bzuillsmith** [comment]
Thanks guys, I'm going to close this for now as out of scope of the project. Feel free to reopen if you wish to discuss this topic any further.
