### ISSUE TITLE
DXF parser to DXF file

### ISSUE THREAD

**Issue by Dbroqua** [gdsestimating/dxf-parser#18]
Hello,

For one project I need to extract some layers of one DXF file to generate another DXF file.

I thank use dxf-parser to generate the list of my layers but how transform the JSON object in new DXF file..

Do you have any idea how I can do this ?

Regards,
Damien

**Comment by Dbroqua** [comment]
Hello,

Really sad news for me :'( .

Regards,
Damien

**Comment by iceblu3710** [comment]
@Dbroqua Check out dxflib, it has easy calls to write each section and dxf-parser conveniently breaks out the sections for you. Should be able to write a go-between.

**Comment by Dbroqua** [comment]
Hello @iceblu3710 ,

Ok, I will check out dxflib (same if I don't make C++ since 10 years :D ).

Regards,
Damien
