### ISSUE TITLE
Add Support for Polyline

### ISSUE THREAD

**Issue by mankyd** [gdsestimating/dxf-parser#2]
LWPolyline works. More general Polylines, however, do not: http://www.autodesk.com/techpubs/autocad/acad2000/dxf/polyline_dxf_06.htm

**Comment by bzuillsmith** [comment]
Ah, good point. I didn't understand the difference until now. I'm still a cad newbie :)

It'd be good to get this working I'll work on that next.

**Comment by mankyd** [comment]
I've started hacking on it a bit, though I don't know how much progress I'll make today. For consistency, it looks like you'll want to rename "parserPolylineVertices" into "parserPolylinePoints", and then create a new "parserPolylineVertices" that actually parses VERTEX's until it encounters a SEQEND.

**Comment by bzuillsmith** [comment]
Sounds like good changes to me. Go ahead and hack away! :)

What's there was written rather quickly. If you find a nicer way to reorganize things, feel free to take a stab at that as well. I've considered separating the parser into multiple files. Hard to say if that would be better or make it harder to navigate the code. Guess it also depends on the tools you're using.
