### ISSUE TITLE
Parse Splines

### ISSUE THREAD

**Issue by iparrabb** [gdsestimating/dxf-parser#27]
Hey there,

Is possible parse Splines with this library?, If not, any way for this purpose?

Thanks in advance.

**Comment by goatchurchprime** [comment]
If you do implement this, pay particular note to non-uniform rational splines, such as this an example.  
[Problem splines.dxf.zip](https://github.com/gdsestimating/dxf-parser/files/1593866/Problem.splines.dxf.zip)

I happened to encounter this example when finding a problem in an old version of librecad, and identified that this was the patch that fixed it.
   https://github.com/LibreCAD/LibreCAD/commit/765ee0e3cf8d6f690d8695a16bf2bbd6d521130d

This is just to provide a headstart as to where there's some code that could potentially be scavenged for this difficult issue.

**Comment by iparrabb** [comment]
Thanks @goatchurchprime, finally we will use [this package for nodejs](https://github.com/bjnortier/dxf) that solves this problem.

**Comment by goatchurchprime** [comment]
I can confirm that the package referred gets those splines right.  (*sigh* Being a python programmer I had been trying to avoid node)

**Comment by bzuillsmith** [comment]
I just added support for this in the latest commit. I've got a few other things to clean up before I publish. You can see an example of the Spline output in the test [for it here](https://github.com/gdsestimating/dxf-parser/blob/master/test/data/splines.expected.json). Note that the three-dxf library doesn't support drawing splines yet and is a separate issue.

**Comment by iparrabb** [comment]
Wow, awesome @bzuillsmith , thanks for the effort.

**Comment by bzuillsmith** [comment]
Published in 5.0
