### ISSUE TITLE
ReferenceError: checkCommonEntityProperties is not defined

### ISSUE THREAD

**Issue by tiagotalo** [gdsestimating/dxf-parser#32]
First, thanks for the contributors for this very nice library.

I am using a dxf-parser (last master version) to read a dxf file (3D face I think).
When parsing the file, I am getting an error:

```
ReferenceError: checkCommonEntityProperties is not defined
    at EntityParser.parseEntity (dxf-parser.js:1296)
    at parseEntities (dxf-parser.js:1070)
    at parseAll (dxf-parser.js:531)
    at DxfParser._parse (dxf-parser.js:1127)
    at DxfParser.parseSync (dxf-parser.js:463)
```

I am not understanding why I am getting this error.
In case someone could give some hints to understand what I did wrong, that would be nice.

I looked in the opened and closed issues of this github, but I did not find similar post.

Here is the file (in txt format as github won't accept *.dxf)
 [my3Ddxf.txt](https://github.com/gdsestimating/dxf-parser/files/1829616/my3Ddxf.txt)

**Comment by Serthys** [comment]
I tried opening your file with the sample from https://github.com/gdsestimating/three-dxf and it works with no errors.
![image](https://user-images.githubusercontent.com/13573099/37677369-27de8cea-2c7b-11e8-96ed-834d9970b4eb.png)

**Comment by tiagotalo** [comment]
Thank you very much for trying my data.
So I guess it is because of my setup. I did not install it through npm.

I  am working an django project inside a docker.
 I copy pasted the dist/dxf-parse.js in my project and loaded.

So I might be missing so dependencies ? Sorry, I am not very experimented with npm

Or would it be because of my code ? here is a sample:
```
	upload_file(ev) {
	 ev.preventDefault();
        const file = document.getElementById('dxf-uploaded-file').files[0];
        const name = file.name;
        const type = file.type;
        const size = file.size;

        const reader = new FileReader();
        reader.onload = function(){
             const text = reader.result;
             console.log(reader.result.substring(0, 200));
              try {
          		const parser = new DxfParser();
    			const dxf = parser.parseSync(text);
    			console.log(dxf);
    			const cadCanvas = new ThreeDxf.Viewer(dxf, document.getElementById('dxf-preview'), 400, 400);
			}catch(err) {
    			return console.error(err.stack);
			}
        };
```

I guess I can install npm for django ! :+1:

**Comment by bzuillsmith** [comment]
I'm not sure why you'd be getting that error. In your browser, are there any other errors in the development console or any trouble loading source files?

**Comment by bzuillsmith** [comment]
Since I haven't heard anything more, I'm going to close this as not a bug. Feel free to reopen if you wish to work through it further.
