### ISSUE TITLE
Big MTEXT Parsing bug

### ISSUE THREAD

**Issue by xlionis** [gdsestimating/dxf-parser#36]
Hello 

I spot an bug in the code while trying to read a big MTEXT.

I corrected it by modifying the following code in the mtext.js file

from

case 1:
    entity.text = curr.value;
    break;
case 3:
    entity.text + = curr.value;
    break;

to

case 1:
     entity.text? entity.text + = curr.value : entity.text = curr.value;
     break;
case 3:
     entity.text? entity.text += curr.value : entity.text = curr.value;
     break;

thanks for your great work
xlionis

**Comment by bzuillsmith** [comment]
Interesting, so you came across a case where code 3 came before code 1?

This seems like a reasonable fix, thanks.

**Comment by bzuillsmith** [comment]
I've commited this code. Haven't published yet, but hope to soon. Thanks for the bug report and fixed code!
