### ISSUE TITLE
Polyline extrusion direction not set

### ISSUE THREAD

**Issue by Serthys** [gdsestimating/dxf-parser#39]
On 
https://github.com/gdsestimating/dxf-parser/blob/master/lib/entities/polyline.js#L44 and on dist 
https://github.com/gdsestimating/dxf-parser/blob/master/dist/dxf-parser.js#L1979.

Is that intended or a mistake?

**Comment by bzuillsmith** [comment]
Somehow never saw this. Those source files have changed now. Was it just an inconsistency between the source and dist? I see line 42 of polyline.js has an extrusionDirection...

**Comment by bzuillsmith** [comment]
Actually, I see from a PR what the problem is. Should have been ```entity.extrusionDirection = ...``` I'll get that merged in soon and publish
