### ISSUE TITLE
String Base 64

### ISSUE THREAD

**Issue by Sphinxs** [gdsestimating/dxf-parser#44]
Is there a way to parse a file that was get via `event.target.files[0]`, type `string` (Base 64) ? When I try to parse `let dxf = parser.parseSync(this.state.data);` I receive an error: `Empty File` in the function `_parse` (**node_modules/dxf-parser/lib/DxfParser.js**).

Example of string:

![image](https://user-images.githubusercontent.com/19755014/52516370-fe5b3580-2c10-11e9-87cb-3c5985226ace.png)

**Comment by Serthys** [comment]
You can use [atob()](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding) to convert the base64 back to text. [Sample](https://stackblitz.com/edit/js-auujcv?file=input-file.js).
