### ISSUE TITLE
Unintentional skipping of Group code

### ISSUE THREAD

**Issue by trubit** [gdsestimating/dxf-parser#47]
https://github.com/gdsestimating/dxf-parser/blob/887a26af9181c62bb5d016b606882d9897f5b7d7/src/entities/lwpolyline.js#L94

When we are on this lane because we detected group code NOT from VERTEX but from LWPOLYLINE, we should call 

```javascript
scanner.rewind();
```

before returning. 
So when we jump back to looping over LWPOLYLINE group codes, we dont skip one.
Effectively this skips 210 code which is `extrusionDirectionX` and it is missing from entity.

Easy fix and makes sense :)

**Comment by bzuillsmith** [comment]
Good catch. Thanks for looking into this. I'm happy to take a pull request. Otherwise I'll get to it next time I work on this project.
