### ISSUE TITLE
Vertex returns incorrect bulge value in some cases

### ISSUE THREAD

**Issue by mattegan** [gdsestimating/dxf-parser#50]
A vertex with a start and end width defined, but a bulge value of 0 returns a non-zero bulge.

I think there is a missing "break" statement after case 40 and case 41 in the vertex parser. Case 41 is hit for the end width, which falls through to case 42. Since the end width is nonzero (curr.value != 0) evaluates to true and the bulge is set to the end width. When the bulge is parsed, and case 42 is hit again, the bulge is actually 0, which then fails to zero or remove the bulge property.

Adding a "break" to case 41 fixes the issue.

If you need, I can try and figure out how to submit a pull request!

**Comment by Serthys** [comment]
Here's [a link to the relevant code](https://github.com/gdsestimating/dxf-parser/blob/887a26af9181c62bb5d016b606882d9897f5b7d7/src/entities/vertex.js#L26).

I think you explanation makes sense.

**Comment by bzuillsmith** [comment]
Ah yes. I work with a lot of Visual Basic legacy code and case statements don't fall through in that language. I seem to have forgotten this when committing this code.
