### ISSUE TITLE
Uncaught TypeError: window.DxfParser is not a constructor

### ISSUE THREAD

**Issue by thedanieljk** [gdsestimating/dxf-parser#51]
I get an error when trying to call `var parser = new window.DxfParser` 

The error is 
```
TypeError: window.DxfParser is not a constructor
    at window.onload
```

dxf-parser.js is included in the head of the html file and I can see dxf-parser.js is loaded in the sources.

**Comment by Serthys** [comment]
Have you tried running the sample?
Here's the [sample permalink](https://github.com/gdsestimating/dxf-parser/blob/887a26af9181c62bb5d016b606882d9897f5b7d7/samples/browser/index.html).

**Comment by thedanieljk** [comment]
I'm able to get the sample working but can't get things to work in my liferay tomcat server.

**Comment by Serthys** [comment]
On the [sample](https://github.com/gdsestimating/dxf-parser/blob/887a26af9181c62bb5d016b606882d9897f5b7d7/samples/browser/index.html#L21) the parser is instanced like this:
```
var parser = new DxfParser();
```
Have you tried that?

**Comment by thedanieljk** [comment]
I've tried that, that gives me `Uncaught ReferenceError: DxfParser is not defined
    at window.onload`

For reference, the end goal is to securely display a dxf from a url using three-dxf.

**Comment by Serthys** [comment]
I managed to get [a working example](https://stackblitz.com/edit/typescript-q3hqnx?file=index.html), I've never user javascript modules like this so it took me a while.

The index on the same is the same as the same here except for the import of the `dxf-parser.js`.
I load the `dxf-parser.js` on `index.js`, import de module there and set the `window.DxfParser` value so the `index.hml` can use it.
The `dxf-parser.js` on the sample is made by running `npm run build` with a change on the `webpack.config.js`. I changed the property `libraryExport: 'default'` to `libraryExport: 'this'`.

**Comment by thedanieljk** [comment]
Thank you very much for your help. Using your copy of dxf-parser.js, I appear to be successfully parsing my files. Could you please reiterate the steps you took to generate that dxf-parser.js file? I'm confused as to why the one I was using is different.

**Comment by Serthys** [comment]
You are welcome, remember to close the issue if it's already solved.

**Comment by bzuillsmith** [comment]
Thanks for helping with this @Serthys 

I was last working toward modularizing this library to work better with react, angular or other module-oriented libraries. Sorry I have not been very responsive. Been a bit overwhelmed between work and moving. :)
