### ISSUE TITLE
How to measure the maximum coordinates of a dxf file.

### ISSUE THREAD

**Issue by jiantaolovebingbing** [gdsestimating/dxf-parser#63]
How to measure the maximum coordinates of a dxf file. Like a svg file, it has the viewbox attribute

**Comment by Serthys** [comment]
If you run the sample up to:

> node samples/node/parseSync

you will have an out.json file with the parsed content. The drawn staff is usually under the entities array, there you can iterate and calculate anything you want.

**Comment by bzuillsmith** [comment]
The challenge of this will be that if your DXF contains blocks, you must consider the INSERT position of the block + the coordinates of the entities within the block which could themselves be more block INSERTs I think. It's not the easiest task if you have to handle every kind of entity. Such a function is outside the scope of this library

**Comment by jiantaolovebingbing** [comment]
OK, thx! I have solved it.
