### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Expected code for point value to be 20 but got 11

### ISSUE THREAD

**Issue by jiantaolovebingbing** [gdsestimating/dxf-parser#64]
###  Error: Expected code for point value to be 20 but got 11.
    at c (...\node_modules\dxf-parser\dist\dxf-parser.js:1:7523)

When i test serveral  dxf   file , some error showed .  How does it happend?

my dxf link 
[https://cdn.thingiverse.com/assets/5e/78/f6/e8/b1/woodenPenStand115_4mm_Funlab.dxf](url)

**Comment by bzuillsmith** [comment]
In this file, some of the coordinates appear to be mixed together. For instance:
A typical x,y,z coordinate is saved with codes 10,20,30 respectively. Some entities have more coordinates encoded with codes like 11, 21, 31, or 12,22,32 etc.  It is usually the case that these coordinates are found in the file sequentially. However, in your file, they are mixed together. For example, the following codes `10,11,12,20,21,22` are representing something like `x1, x2, x3, y1, y2, y3` in that order. This parser expects them to happen in the order `x1, y1, x2, y2, x3, y3`

The dxf file you gave is 'technically' valid according, but this is the first time I have seen this issue. Do you know what program produced this file?

**Comment by jiantaolovebingbing** [comment]
I don't know what program generated it. I just downloaded it from thingiverse. I want to test the library's support for dxf files. Is the library just like readme said, just does not support those three types.
### 3DSolids
### All types of Leaders
### other less common objects and entities.

One more things, when i use three-dxf, it's  drawing  speed in threejs is too slow. What can i do to 
improve it‘s drawing speed ?

Thanks a lot .

**Comment by jiantaolovebingbing** [comment]
I made some attempts, for example, change `getPiont (100)` to `getPiont (50)`, but this effect is not obvious

**Comment by Serthys** [comment]
@bzuillsmith I've seen the the codes out of order before, I thought the parser handled the data that way because I've seen switch in most places. The order of codes should not be assumed to be in any sequence.

**Comment by bzuillsmith** [comment]
This is probably true. We have to make a distinction between entity coordinate properties, and a sequences of coordinates. In the case of a sequence for things like polylines, we of course must account for the order. But for something like a basic line with a startPoint and endPoint coordinate, it should not matter.

**Comment by jiantaolovebingbing** [comment]
If possible I will new a pr to three-dxf. 
Can the current ^ 1.0.0-alpha.2 be upgraded to 0.4.9
