### ISSUE TITLE
Support for pdf

### ISSUE THREAD

**Issue by sivayekula** [gdsestimating/dxf-parser#72]
I have a pdf file with multiple dxf images. I have attached sample pdf. Please help me how to extract this pdf using javascript/nodeJs. Please let me know any
[Sample Vector PDF_outlines.pdf](https://github.com/gdsestimating/dxf-parser/files/6703826/Sample.Vector.PDF_outlines.pdf)
 suggestions. Thanks

**Comment by bzuillsmith** [comment]
Hi, PDF files are not a simple format to parse. You'll need to look for a project that can get the DXF data out of the PDF as plain text, then use this library to parse that text. You aren't likely to find anyone who knows how to parse PDFs here and it is outside the scope of this project
