### ISSUE TITLE
DxfParser export seems broken

### ISSUE THREAD

**Issue by pentacular** [gdsestimating/dxf-parser#78]
DxfParser is exported as undefined

I've been able to work around this by

```js
import dxfParserModule from 'dxf-parser';
const DxfParser = dxfParserModule.default;
```

but this should probably be fixed more nicely sometime.

**Comment by bzuillsmith** [comment]
Yes, you're right. I should not have deployed v1.1.0. I thought I had tested the export to be sure it was the same as v1.0.1 but it clearly I did not do it right. I'll redeploy it with the proper exports
