### ISSUE TITLE
npm or yarn?

### ISSUE THREAD

**Issue by gpbmike** [gdsestimating/dxf-parser#81]
I see both package-lock.json and yarn.lock files in the repo. 

Running `npm install` modifies both `package.json` and `package-lock.json`.

Running `yarn install` modifies `yarn.lock`.

The [contributing wiki](https://github.com/gdsestimating/dxf-parser/wiki) does not indicate a preference.

Seems like one of the lock files should be removed and the other should be updated and committed.

I'm not the most proficient `npm`/`yarn` user so I apologize if I am missing something obvious here.

# package-lock.json changes after `npm install`
![image](https://user-images.githubusercontent.com/8754/140825319-e0a3c05b-8d7a-4400-a911-f4de881d7efb.png)

# yarn.lock changes after `yarn install` (truncated)
![image](https://user-images.githubusercontent.com/8754/140825503-0ae2136e-1919-41a3-a64d-2eb495ce2906.png)

**Comment by bzuillsmith** [comment]
ah, thanks for pointing that out. I don't believe I've ever used yarn so it probably came from another contributor and I missed it. I'll remove it in favor of npm.
